services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      URI: ${URI}
      PRIVATE_KEY: ${PRIVATE_KEY}
      GMAIL_ACCOUNT: ${GMAIL_ACCOUNT}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
      BASE_URL: ${BASE_URL}
